openapi: 3.0.0
info:
  title: Push API
  description: API for pushing text payloads
  version: 1.0.0
servers:
  - url: localhost:9098
paths:
  /push:
    post:
      summary: Push text data
      description: Endpoint to push text payload to the server
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: Text payload to be pushed
      responses:
        '200':
          description: Successfully pushed the text data
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Text payload received"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Invalid payload"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Internal server error"
